### ISSUE TITLE
Error to do with code pointing to somewhere on Sam computer I believe.

### ISSUE THREAD

**Issue by phil-bell** [502BadGateway/project_2#14]
Philips-MacBook-Pro:project_2 Phil$ python main.py
Please input a location: Warwick
Warwick, UK
(52.28231599999999, -1.584927)
(52.28231599999999, -1.584927)
52.28231599999999,-1.584927
http://maps.googleapis.com/maps/api/staticmap?center=52.28231599999999,-1.584927&zoom=16&format=png&sensor=false&size=640x480&maptype=roadmap&style=element:labels|visibility:off
Size of image:
(640, 480)
480 640

64 48
Size of im_arr
48
Traceback (most recent call last):
  File "main.py", line 172, in <module>
    main()
  File "main.py", line 129, in main
    arena = gen_arena.arena(mapName+".png") 
  File "/Users/Phil/project_2/gen_arena.py", line 99, in **init**
    cp.save("/home/samathy/maptst/"+str(row)+"_"+str(col), "PNG")  #Here for debug
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PIL/Image.py", line 1433, in save
    fp = __builtin__.open(fp, "wb")
IOError: [Errno 2] No such file or directory: '/home/samathy/maptst/0_0'

**Comment by Samathy** [comment]
Removed problem line. Pull to get updated code.

**Comment by phil-bell** [comment]
How does removing the line fix it, the same error message is coming up

**Comment by phil-bell** [comment]
Traceback (most recent call last):
  File "main.py", line 172, in <module>
    main()
  File "main.py", line 129, in main
    arena = gen_arena.arena(mapName+".png")
  File "F:\project_2\gen_arena.py", line 43, in **init**
    __tmp_image = Image.open(image) #get a copy of the image
  File "C:\PYTHON27\lib\site-packages\PIL\Image.py", line 2274, in open
    % (filename if filename else fp))
IOError: cannot identify image file 'map1.png'

**Comment by Samathy** [comment]
Thats a different issue.

The former is a debug line in gen_arena.py which is completely unnecessary. So i removed it. Fixing that issue.

The latter is an issue in gen_arena.py but on a different line. Not sure why thats not working in your environment, it should do, because it doesnt have any hardcoded paths. 

Could be an issue if you're running python from Sublime because it might be that python's working directory is not where main.py is being run from. Try running python from within the same directory as main.py instead of through Sublime.

**Comment by phil-bell** [comment]
I'm running it in command prompt.

**Comment by Samathy** [comment]
I can't replicate in my environment, we'll have a look together tomorrow.

**Comment by Samathy** [comment]
Am I assigned to the first issue,  or the second one?

**Comment by danbeglin** [comment]
From what Phil said to me, we cannot  run it at all since a lot of the paths are to your laptop. I've assigned it based on what he told me last night, but he needs to clarify.
