### ISSUE TITLE
Pygame wont open JPG 

### ISSUE THREAD

**Issue by phil-bell** [502BadGateway/project_2#4]
file created by urllib libary is a JPG but for some reason pygame will only open BMP, might have to convert the file or find a way to make pygame open JPG.

**Comment by Samathy** [comment]
Python Image library will can open JPG images and save PNGs. Could use PIL to convert?

**Comment by phil-bell** [comment]
ended up being a issue with my pygame install, I re installed it and it still wont open JPG or save as BMP but it can be saved and opened as a PNG
