### ISSUE TITLE
The image does not fill the window 

### ISSUE THREAD

**Issue by phil-bell** [502BadGateway/project_2#5]
the image does not fill the window and there is a long error message.

"libpng warning: Ignoring bad adaptive filter type
libpng warning: Extra compressed data.
libpng warning: Extra compression data
2015-01-11 15:26:13.935 Python[7214:d07] Warning once: This application, or a library it uses, is using NSQuickDrawView, which has been deprecated. Apps should cease use of QuickDraw and move to Quartz.
Jan 11 15:26:13 Philips-MacBook-Pro.local Python[7214] <Error>: The function `CGSFlushWindow' is obsolete and will be removed in an upcoming update. Unfortunately, this application, or a library it uses, is using this obsolete function, and is thereby contributing to an overall degradation of system performance. Please use`CGSFlushWindowContentRegion' instead."

I will try the fix suggested in the error message.

**Comment by phil-bell** [comment]
ok fix from the error message brings back the BMP error from before

**Comment by phil-bell** [comment]
Is now in a state where is works most of the time and then some times the error message:

<Error>libpng warning: Ignoring bad adaptive filter type
libpng error: IDAT: CRC error
Traceback (most recent call last):
  File "pygeo.py", line 57, in <module>
    Geo()
  File "pygeo.py", line 48, in **init**
    self.background = pygame.image.load(imageScreenShot).convert
pygame.error: Error reading the PNG file.</Error>

**Comment by Samathy** [comment]
Fixed the later issue by making sure script closes file resources after writing to them.
